FROM python:3.9-slim

COPY ./requirements_bot.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./src/bot /app/src

WORKDIR /app/src

CMD ["python", "run_bot.py"]