version: '3'
services:
  app:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
    ports:
      - "80:80"
    networks:
      - mynet
    cpus: 4
  bot:
    build:
      context: ./src/bot
      dockerfile: Dockerfile
    depends_on:
      - app
    networks:
      - mynet
    secrets:
      - token
    cpus: 4

networks:
  mynet:
    external: true

secrets:
  token:
    environment: BOT_TOKEN