version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - ./models:/app/models
    ports:
      - "80:80"
    networks:
      - mynet
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - app
    networks:
      - mynet
    secrets:
      - token

networks:
  mynet:
    external: true

secrets:
  token:
    environment: BOT_TOKEN