FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim

COPY ./requirements_api.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./src/api /app/src

WORKDIR /app/src

CMD ["uvicorn", "frontend:app", "--workers", "4", "--timeout-keep-alive", "1000", "--host", "0.0.0.0", "--port", "80"]